name             'rackspace_gluster'
maintainer       'Rackspace'
maintainer_email 'rackspace-cookbooks@rackspace.com'
license          'All rights reserved'
description      'Installs/Configures gluster server for rackspace'
version          '1.0.0'

depends 'apt'
depends 'chef-sugar'
depends 'yum'
depends 'yum-ius'
depends 'yum-epel'

supports 'debian'
supports 'ubuntu'
